[package]
name = "services_grouping"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = {version = "0.24.0" }
serde = { version = "1.0.197", features = ["derive"] }
log = "0.4.21"
pretty_env_logger = "0.5.0"
